language: node_js

node_js:
  - stable
  - 8
  - 7
  - 6

install:
  - npm install

script:
  - npm test

after_success:
   - npm run coverage
   - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/